kind = "web"
previewPath = "/"
title = "Trua IO"
version = "1.0.0"
id = "artifacts/trua-io"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22048

[services.development]
run = "pnpm --filter @workspace/trua-io run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/trua-io", "run", "build" ]
publicDir = "artifacts/trua-io/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22048"
BASE_PATH = "/"
